/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.CallCenter;
import controlador.Empleado;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import modelo.modelEmpleado;

/**
 *
 * @author icast
 */
public class frmPrincipal extends javax.swing.JFrame {

    // Atributos
    LinkedList<Empleado> empleadoLista = new LinkedList<>();
    CallCenter liquidacion = new CallCenter();
    modelEmpleado mdEmpleado = new modelEmpleado();
    Empleado empleado;
    
    public frmPrincipal() {
        initComponents();
        this.empleadoLista = mdEmpleado.listaEmpleado();
        this.listaEmpleado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneGrupo = new javax.swing.JTabbedPane();
        jPanelLiqNomina = new javax.swing.JPanel();
        jPanelConsulta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jButtonConsultar = new javax.swing.JButton();
        jPanelInfoEmpleado = new javax.swing.JPanel();
        jPanelDatoSalario = new javax.swing.JPanel();
        jLabelInfNomina = new javax.swing.JLabel();
        jLabelSalario = new javax.swing.JLabel();
        jLabelvlrHoraExtra = new javax.swing.JLabel();
        jCheckBoxauxTransp = new javax.swing.JCheckBox();
        jTextFieldSalario = new javax.swing.JTextField();
        jTextFieldvlrHoraExtra = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApellido = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jButtonGenerarNomina = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelTotalNomina = new javax.swing.JLabel();
        jTextFieldNomina = new javax.swing.JTextField();
        jLabelTotalPrestacion = new javax.swing.JLabel();
        jTextFieldTotalPrestaciones = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanelInfoEmpleadoCrear = new javax.swing.JPanel();
        jPanelDatoSalario1 = new javax.swing.JPanel();
        jLabelInfNomina1 = new javax.swing.JLabel();
        jLabelSalario1 = new javax.swing.JLabel();
        jLabelvlrHoraExtra1 = new javax.swing.JLabel();
        jCheckBoxauxTransp1 = new javax.swing.JCheckBox();
        jTextFieldSalario1 = new javax.swing.JTextField();
        jTextFieldvlrHoraExtra1 = new javax.swing.JTextField();
        jLabelNombre1 = new javax.swing.JLabel();
        jTextFieldNombre1 = new javax.swing.JTextField();
        jLabelApellido1 = new javax.swing.JLabel();
        jTextFieldApellido1 = new javax.swing.JTextField();
        jButtonGuardarEmpleado = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCedula = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelInfoEmpleadoCrear1 = new javax.swing.JPanel();
        jPanelDatoSalario2 = new javax.swing.JPanel();
        jLabelInfNomina2 = new javax.swing.JLabel();
        jLabelSalario2 = new javax.swing.JLabel();
        jLabelvlrHoraExtra2 = new javax.swing.JLabel();
        jCheckBoxauxTransp2 = new javax.swing.JCheckBox();
        jTextFieldSalario2 = new javax.swing.JTextField();
        jTextFieldvlrHoraExtra2 = new javax.swing.JTextField();
        jLabelNombre2 = new javax.swing.JLabel();
        jTextFieldNombre2 = new javax.swing.JTextField();
        jLabelApellido2 = new javax.swing.JLabel();
        jTextFieldApellido2 = new javax.swing.JTextField();
        jButtonEditarEmpleado1 = new javax.swing.JButton();
        jPanelConsulta1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabelCodigo1 = new javax.swing.JLabel();
        jTextFieldCodigo1 = new javax.swing.JTextField();
        jButtonConsultarEditar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanelConsulta2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabelCodigo2 = new javax.swing.JLabel();
        jTextFieldCodigo2 = new javax.swing.JTextField();
        jButtonConsultarEditar1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListEmpleado = new javax.swing.JList<>();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButtonProcesoMasivo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListLiqMasiva = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanelConsulta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Consultar Empleado");

        jLabelCodigo.setText("Codigo:");

        jTextFieldCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButtonConsultar.setText("Consultar Empleado");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelConsultaLayout = new javax.swing.GroupLayout(jPanelConsulta);
        jPanelConsulta.setLayout(jPanelConsultaLayout);
        jPanelConsultaLayout.setHorizontalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConsultaLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelConsultaLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jButtonConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelConsultaLayout.setVerticalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigo)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonConsultar)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanelInfoEmpleado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanelDatoSalario.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDatoSalario.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabelInfNomina.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelInfNomina.setText("Informacion Nomina Empleado");

        jLabelSalario.setText("Salario:");
        jLabelSalario.setToolTipText("");

        jLabelvlrHoraExtra.setText("Valor Horas Extras:");

        jCheckBoxauxTransp.setText("Auxilio Transporte");

        jTextFieldSalario.setEditable(false);
        jTextFieldSalario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextFieldvlrHoraExtra.setEditable(false);
        jTextFieldvlrHoraExtra.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanelDatoSalarioLayout = new javax.swing.GroupLayout(jPanelDatoSalario);
        jPanelDatoSalario.setLayout(jPanelDatoSalarioLayout);
        jPanelDatoSalarioLayout.setHorizontalGroup(
            jPanelDatoSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatoSalarioLayout.createSequentialGroup()
                .addGroup(jPanelDatoSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelDatoSalarioLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabelInfNomina))
                    .addGroup(jPanelDatoSalarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelSalario)
                        .addGap(73, 73, 73)
                        .addComponent(jTextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDatoSalarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelvlrHoraExtra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldvlrHoraExtra))
                    .addGroup(jPanelDatoSalarioLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jCheckBoxauxTransp)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanelDatoSalarioLayout.setVerticalGroup(
            jPanelDatoSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatoSalarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInfNomina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatoSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSalario)
                    .addComponent(jTextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanelDatoSalarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelvlrHoraExtra)
                    .addComponent(jTextFieldvlrHoraExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxauxTransp)
                .addGap(17, 17, 17))
        );

        jLabelNombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelNombre.setText("Nombre:");

        jTextFieldNombre.setEditable(false);
        jTextFieldNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabelApellido.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelApellido.setText("Apellido:");
        jLabelApellido.setToolTipText("");

        jTextFieldApellido.setEditable(false);
        jTextFieldApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButtonGenerarNomina.setText("Generar Nomina");
        jButtonGenerarNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarNominaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInfoEmpleadoLayout = new javax.swing.GroupLayout(jPanelInfoEmpleado);
        jPanelInfoEmpleado.setLayout(jPanelInfoEmpleadoLayout);
        jPanelInfoEmpleadoLayout.setHorizontalGroup(
            jPanelInfoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfoEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNombre)
                    .addComponent(jLabelApellido)
                    .addGroup(jPanelInfoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldApellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jPanelDatoSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelInfoEmpleadoLayout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jButtonGenerarNomina, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelInfoEmpleadoLayout.setVerticalGroup(
            jPanelInfoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoEmpleadoLayout.createSequentialGroup()
                .addGroup(jPanelInfoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoEmpleadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabelApellido)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInfoEmpleadoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanelDatoSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonGenerarNomina)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelTotalNomina.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTotalNomina.setText("Total Nomina Empleado:");

        jTextFieldNomina.setEditable(false);
        jTextFieldNomina.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTextFieldNomina.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldNomina.setText("0");

        jLabelTotalPrestacion.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTotalPrestacion.setText("Total Prestaciones:");

        jTextFieldTotalPrestaciones.setEditable(false);
        jTextFieldTotalPrestaciones.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTextFieldTotalPrestaciones.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldTotalPrestaciones.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabelTotalNomina))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTotalPrestacion)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNomina, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(jTextFieldTotalPrestaciones))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTotalNomina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalPrestacion)
                    .addComponent(jTextFieldTotalPrestaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout jPanelLiqNominaLayout = new javax.swing.GroupLayout(jPanelLiqNomina);
        jPanelLiqNomina.setLayout(jPanelLiqNominaLayout);
        jPanelLiqNominaLayout.setHorizontalGroup(
            jPanelLiqNominaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLiqNominaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLiqNominaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelInfoEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanelLiqNominaLayout.setVerticalGroup(
            jPanelLiqNominaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLiqNominaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelInfoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPaneGrupo.addTab("Liq. Nomina", jPanelLiqNomina);

        jPanelInfoEmpleadoCrear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanelDatoSalario1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDatoSalario1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabelInfNomina1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelInfNomina1.setText("Informacion Nomina Empleado");

        jLabelSalario1.setText("Salario:");
        jLabelSalario1.setToolTipText("");

        jLabelvlrHoraExtra1.setText("Valor Horas Extras:");

        jCheckBoxauxTransp1.setText("Auxilio Transporte");

        jTextFieldSalario1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldSalario1.setText("0");

        jTextFieldvlrHoraExtra1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldvlrHoraExtra1.setText("0");

        javax.swing.GroupLayout jPanelDatoSalario1Layout = new javax.swing.GroupLayout(jPanelDatoSalario1);
        jPanelDatoSalario1.setLayout(jPanelDatoSalario1Layout);
        jPanelDatoSalario1Layout.setHorizontalGroup(
            jPanelDatoSalario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatoSalario1Layout.createSequentialGroup()
                .addGroup(jPanelDatoSalario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatoSalario1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabelInfNomina1))
                    .addGroup(jPanelDatoSalario1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jCheckBoxauxTransp1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelDatoSalario1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatoSalario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSalario1)
                    .addComponent(jLabelvlrHoraExtra1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanelDatoSalario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldvlrHoraExtra1)
                    .addComponent(jTextFieldSalario1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        jPanelDatoSalario1Layout.setVerticalGroup(
            jPanelDatoSalario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatoSalario1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInfNomina1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatoSalario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatoSalario1Layout.createSequentialGroup()
                        .addComponent(jLabelSalario1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelvlrHoraExtra1))
                    .addGroup(jPanelDatoSalario1Layout.createSequentialGroup()
                        .addComponent(jTextFieldSalario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jTextFieldvlrHoraExtra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxauxTransp1)
                .addGap(17, 17, 17))
        );

        jLabelNombre1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelNombre1.setText("Nombre:");

        jTextFieldNombre1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabelApellido1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelApellido1.setText("Apellido:");
        jLabelApellido1.setToolTipText("");

        jTextFieldApellido1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButtonGuardarEmpleado.setText("Guardar");
        jButtonGuardarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarEmpleadoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Cedula:");

        jTextFieldCedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanelInfoEmpleadoCrearLayout = new javax.swing.GroupLayout(jPanelInfoEmpleadoCrear);
        jPanelInfoEmpleadoCrear.setLayout(jPanelInfoEmpleadoCrearLayout);
        jPanelInfoEmpleadoCrearLayout.setHorizontalGroup(
            jPanelInfoEmpleadoCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoEmpleadoCrearLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoEmpleadoCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldCedula, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(jLabelNombre1)
                    .addComponent(jLabelApellido1)
                    .addComponent(jTextFieldApellido1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(jTextFieldNombre1)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanelInfoEmpleadoCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfoEmpleadoCrearLayout.createSequentialGroup()
                        .addComponent(jPanelDatoSalario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfoEmpleadoCrearLayout.createSequentialGroup()
                        .addComponent(jButtonGuardarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))))
        );
        jPanelInfoEmpleadoCrearLayout.setVerticalGroup(
            jPanelInfoEmpleadoCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoEmpleadoCrearLayout.createSequentialGroup()
                .addGroup(jPanelInfoEmpleadoCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoEmpleadoCrearLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelNombre1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelApellido1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7))
                    .addGroup(jPanelInfoEmpleadoCrearLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanelDatoSalario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInfoEmpleadoCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonGuardarEmpleado)
                    .addComponent(jTextFieldCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Registrar Empleado");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelInfoEmpleadoCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelInfoEmpleadoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        jTabbedPaneGrupo.addTab("Crear Empleado", jPanel2);

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Editar Empleado");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel3)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanelInfoEmpleadoCrear1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanelDatoSalario2.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDatoSalario2.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabelInfNomina2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelInfNomina2.setText("Informacion Nomina Empleado");

        jLabelSalario2.setText("Salario:");
        jLabelSalario2.setToolTipText("");

        jLabelvlrHoraExtra2.setText("Valor Horas Extras:");

        jCheckBoxauxTransp2.setText("Auxilio Transporte");

        jTextFieldSalario2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldSalario2.setText("0");

        jTextFieldvlrHoraExtra2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldvlrHoraExtra2.setText("0");

        javax.swing.GroupLayout jPanelDatoSalario2Layout = new javax.swing.GroupLayout(jPanelDatoSalario2);
        jPanelDatoSalario2.setLayout(jPanelDatoSalario2Layout);
        jPanelDatoSalario2Layout.setHorizontalGroup(
            jPanelDatoSalario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatoSalario2Layout.createSequentialGroup()
                .addGroup(jPanelDatoSalario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatoSalario2Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabelInfNomina2))
                    .addGroup(jPanelDatoSalario2Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jCheckBoxauxTransp2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelDatoSalario2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatoSalario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSalario2)
                    .addComponent(jLabelvlrHoraExtra2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanelDatoSalario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldvlrHoraExtra2)
                    .addComponent(jTextFieldSalario2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        jPanelDatoSalario2Layout.setVerticalGroup(
            jPanelDatoSalario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatoSalario2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInfNomina2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatoSalario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatoSalario2Layout.createSequentialGroup()
                        .addComponent(jLabelSalario2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelvlrHoraExtra2))
                    .addGroup(jPanelDatoSalario2Layout.createSequentialGroup()
                        .addComponent(jTextFieldSalario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jTextFieldvlrHoraExtra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxauxTransp2)
                .addGap(17, 17, 17))
        );

        jLabelNombre2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelNombre2.setText("Nombre:");

        jTextFieldNombre2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabelApellido2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelApellido2.setText("Apellido:");
        jLabelApellido2.setToolTipText("");

        jTextFieldApellido2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButtonEditarEmpleado1.setText("Guardar Cambios");
        jButtonEditarEmpleado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarEmpleado1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInfoEmpleadoCrear1Layout = new javax.swing.GroupLayout(jPanelInfoEmpleadoCrear1);
        jPanelInfoEmpleadoCrear1.setLayout(jPanelInfoEmpleadoCrear1Layout);
        jPanelInfoEmpleadoCrear1Layout.setHorizontalGroup(
            jPanelInfoEmpleadoCrear1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfoEmpleadoCrear1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoEmpleadoCrear1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNombre2)
                    .addComponent(jLabelApellido2)
                    .addGroup(jPanelInfoEmpleadoCrear1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldApellido2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                        .addComponent(jTextFieldNombre2, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jPanelDatoSalario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelInfoEmpleadoCrear1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jButtonEditarEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelInfoEmpleadoCrear1Layout.setVerticalGroup(
            jPanelInfoEmpleadoCrear1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoEmpleadoCrear1Layout.createSequentialGroup()
                .addGroup(jPanelInfoEmpleadoCrear1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoEmpleadoCrear1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelNombre2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabelApellido2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInfoEmpleadoCrear1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanelDatoSalario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEditarEmpleado1)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanelConsulta1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Consultar Empleado");

        jLabelCodigo1.setText("Codigo:");

        jTextFieldCodigo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButtonConsultarEditar.setText("Consultar Empleado");
        jButtonConsultarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelConsulta1Layout = new javax.swing.GroupLayout(jPanelConsulta1);
        jPanelConsulta1.setLayout(jPanelConsulta1Layout);
        jPanelConsulta1Layout.setHorizontalGroup(
            jPanelConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsulta1Layout.createSequentialGroup()
                .addGroup(jPanelConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConsulta1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(jPanelConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelConsulta1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabelCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelConsulta1Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jButtonConsultarEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelConsulta1Layout.setVerticalGroup(
            jPanelConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsulta1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigo1)
                    .addComponent(jTextFieldCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonConsultarEditar)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(9, 9, 9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelInfoEmpleadoCrear1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelConsulta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelConsulta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelInfoEmpleadoCrear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        jTabbedPaneGrupo.addTab("Editar Empleado", jPanel1);

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("Eliminar Empleado");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel5)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanelConsulta2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Consultar Empleado");

        jLabelCodigo2.setText("Codigo:");

        jTextFieldCodigo2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButtonConsultarEditar1.setText("Eliminar Empleado");
        jButtonConsultarEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarEditar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelConsulta2Layout = new javax.swing.GroupLayout(jPanelConsulta2);
        jPanelConsulta2.setLayout(jPanelConsulta2Layout);
        jPanelConsulta2Layout.setHorizontalGroup(
            jPanelConsulta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsulta2Layout.createSequentialGroup()
                .addGroup(jPanelConsulta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConsulta2Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(jPanelConsulta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelConsulta2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabelCodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelConsulta2Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jButtonConsultarEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelConsulta2Layout.setVerticalGroup(
            jPanelConsulta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsulta2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelConsulta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigo2)
                    .addComponent(jTextFieldCodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonConsultarEditar1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3))
                    .addComponent(jPanelConsulta2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelConsulta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(353, Short.MAX_VALUE))
        );

        jTabbedPaneGrupo.addTab("Eliminar Empleado", jPanel6);

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Lista de Empleados");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(24, 24, 24))
        );

        jListEmpleado.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Empleado 1", "Empleado 2", "Empleado 3", "Empleado 4", "Empleado 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListEmpleado);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPaneGrupo.addTab("Empleados", jPanel8);

        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("Año:");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("2022");
        jTextField1.setToolTipText("");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setText("Mes:");

        jComboBox1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButtonProcesoMasivo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButtonProcesoMasivo.setText("Procesar");
        jButtonProcesoMasivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProcesoMasivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(27, 27, 27)
                        .addComponent(jTextField1))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jButtonProcesoMasivo, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonProcesoMasivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jListLiqMasiva);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneGrupo.addTab("Liq. Masiva Nomina", jPanel10);

        getContentPane().add(jTabbedPaneGrupo);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        // TODO add your handling code here:
  
        empleado = mdEmpleado.consultaEmpleadoId(jTextFieldCodigo.getText());
        
        if(empleado == null){
            JOptionPane.showMessageDialog(rootPane, "Empleado no existe");
            
            jTextFieldNombre.setText("");
            jTextFieldApellido.setText("");
            jTextFieldSalario.setText("");
            jTextFieldvlrHoraExtra.setText("");
            jCheckBoxauxTransp.setSelected(false);
            
            jTextFieldNomina.setText("0");
            jTextFieldTotalPrestaciones.setText("0");
            
        }else{
            
            jTextFieldNombre.setText(empleado.getNombre());
            jTextFieldApellido.setText(empleado.getApellido());
            jTextFieldSalario.setText(String.valueOf(empleado.getSalario()));
            jTextFieldvlrHoraExtra.setText(String.valueOf(empleado.getHorasExtra()));
            jCheckBoxauxTransp.setSelected(empleado.isAuxilioTransporte());
            
            jTextFieldNomina.setText("0");
            jTextFieldTotalPrestaciones.setText("0");
                    
        }
        
        
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void jButtonGenerarNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarNominaActionPerformed
        // TODO add your handling code here:
        
        
        ArrayList<Double> nomina = new ArrayList<>();
        ArrayList<Double> prestacion = new ArrayList<>();
        
        empleado = mdEmpleado.consultaEmpleadoId(jTextFieldCodigo.getText());

        System.out.println("Liquidacion Nomina");
        nomina = liquidacion.liquidarNominaEmp(empleado);
        for (int i = 0; i < nomina.size(); i++) {
            System.out.println(" Total a pagar: " + Math.round(nomina.get(i)));
            jTextFieldNomina.setText(String.valueOf(Math.round(nomina.get(i))));
        }
        System.out.println("Prestaciones Sociales");
        prestacion = liquidacion.liquidarPrestacionesEmp(empleado);
        for (int i = 0; i < prestacion.size(); i++) {
            System.out.println(" Total a pagar: " + Math.round(prestacion.get(i)));
            jTextFieldTotalPrestaciones.setText(String.valueOf(Math.round(prestacion.get(i))));
        }
        
        
    }//GEN-LAST:event_jButtonGenerarNominaActionPerformed

    private void jButtonGuardarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarEmpleadoActionPerformed
        // TODO add your handling code here:

        try {
            if( jTextFieldCedula.getText().equals("")  ||   jTextFieldNombre1.getText().equals("") || jTextFieldApellido1.getText().equals("") || (Integer.valueOf(jTextFieldSalario1.getText()) <= 0) ){
                JOptionPane.showMessageDialog(rootPane, "Los datos del nombre, apellido y salario son obligatorios");
            }else{
                
                empleado = mdEmpleado.validarCedula(jTextFieldCedula.getText());
                
                if(empleado != null){
                    JOptionPane.showMessageDialog(rootPane, "El Empleado ya existe: \n" +
                                                            "Cedula: " + jTextFieldCedula.getText()
                                                          + "Id: \n" + empleado.getId() + " - "   + empleado.getNombre() + " " + empleado.getApellido() ); 
                }else{
                    if(mdEmpleado.crearEmpleado(jTextFieldNombre1.getText(), jTextFieldApellido1.getText(), Integer.valueOf(jTextFieldvlrHoraExtra1.getText()), jCheckBoxauxTransp1.isSelected(), Integer.valueOf(jTextFieldSalario1.getText()), jTextFieldCedula.getText())){

                        JOptionPane.showMessageDialog(rootPane, "Empleado guardado correctamente: \n" + jTextFieldNombre1.getText() +" " + jTextFieldApellido1.getText() ); 

                        jTextFieldNombre1.setText("");
                        jTextFieldApellido1.setText("");
                        jTextFieldCedula.setText("");
                        jTextFieldSalario1.setText("0");
                        jTextFieldvlrHoraExtra1.setText("0");
                        jCheckBoxauxTransp1.setSelected(false);
                        
                        actVistaEmpleado();

                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Empleado NO guardado, intente de nuevo: \n" + jTextFieldNombre1.getText() +" " + jTextFieldApellido1.getText()); 
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error: \n Salario y Horas Extras son datos numericos"); 
        }
    }//GEN-LAST:event_jButtonGuardarEmpleadoActionPerformed

    private void jButtonEditarEmpleado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarEmpleado1ActionPerformed

        
        try {
            if(jTextFieldNombre2.getText().equals("") || jTextFieldApellido2.getText().equals("") || (Integer.valueOf(jTextFieldSalario2.getText()) <= 0) ){
                JOptionPane.showMessageDialog(rootPane, "Los datos del nombre, apellido y salario son obligatorios");
            }else{

                if(mdEmpleado.editarEmpleado(Integer.valueOf(jTextFieldCodigo1.getText()), jTextFieldNombre2.getText(), jTextFieldApellido2.getText(), Integer.valueOf(jTextFieldvlrHoraExtra2.getText()), jCheckBoxauxTransp2.isSelected(), Integer.valueOf(jTextFieldSalario2.getText()))){

                    JOptionPane.showMessageDialog(rootPane, "Empleado editado correctamente: \n" + jTextFieldNombre2.getText() +" " + jTextFieldApellido2.getText() ); 

                    jTextFieldCodigo1.setText("");
                    jTextFieldNombre2.setText("");
                    jTextFieldApellido2.setText("");
                    jTextFieldSalario2.setText("0");
                    jTextFieldvlrHoraExtra2.setText("0");
                    
                    jCheckBoxauxTransp2.setSelected(false);
                    
                    actVistaEmpleado();

                }else{
                    JOptionPane.showMessageDialog(rootPane, "Empleado NO editado, intente de nuevo: \n" + jTextFieldNombre2.getText() +" " + jTextFieldApellido2.getText()); 
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error: \n Salario y Horas Extras son datos numericos"); 
        }
    }//GEN-LAST:event_jButtonEditarEmpleado1ActionPerformed

    private void jButtonConsultarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarEditarActionPerformed
        // TODO add your handling code here:
        empleado = mdEmpleado.consultaEmpleadoId(jTextFieldCodigo1.getText());
        
        if(empleado != null){
            
            jTextFieldNombre2.setText(empleado.getNombre());
            jTextFieldApellido2.setText(empleado.getApellido());
            jTextFieldSalario2.setText(String.valueOf(empleado.getSalario()));
            jTextFieldvlrHoraExtra2.setText(String.valueOf(empleado.getHorasExtra()));
            
            jCheckBoxauxTransp2.setSelected(empleado.isAuxilioTransporte());   
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "Empleado no existe");
        }
    }//GEN-LAST:event_jButtonConsultarEditarActionPerformed

    private void jButtonConsultarEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarEditar1ActionPerformed
        // TODO add your handling code here:

        int confir = JOptionPane.showConfirmDialog(rootPane, "Desea eliminar el empleado con Id: \n" + jTextFieldCodigo2.getText());
        
        System.out.println("Confir: " + confir);
        
        if( confir ==  JOptionPane.YES_OPTION){
            
           if(mdEmpleado.eliminarEmpleado(jTextFieldCodigo2.getText())){
               JOptionPane.showMessageDialog(rootPane, "Empleado eliminado correctamente"); 
               jTextFieldCodigo2.setText("");
               actVistaEmpleado();
            }else{
               JOptionPane.showMessageDialog(rootPane, "Empleado no existe");
           }
            
        }else{
            if( confir == JOptionPane.NO_OPTION){
                JOptionPane.showMessageDialog(rootPane, "Empleado no eliminado");
            }
        }
        
    }//GEN-LAST:event_jButtonConsultarEditar1ActionPerformed

    private void jButtonProcesoMasivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcesoMasivoActionPerformed
        // TODO add your handling code here:
        
        LinkedList<Empleado> empleadoLista = mdEmpleado.listaEmpleado();
        HashMap<Integer, ArrayList> listaNominas = new HashMap<Integer, ArrayList>();
        
        listaNominas = liquidacion.procesoMasivoNominaPrestaciones(empleadoLista);
        
        if(empleadoLista == null || listaNominas == null ){
            JOptionPane.showMessageDialog(rootPane, "No existen datos para procesar");
        }else{
            ListaNominasPrestaciones(listaNominas);
        }
        
    }//GEN-LAST:event_jButtonProcesoMasivoActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    // Mostra Lista de empleados en la vista
    
    private void ListaNominasPrestaciones(HashMap<Integer, ArrayList> listaNominas){
        
        DefaultListModel model = new DefaultListModel();
        int index = 0;
        
        for (ArrayList i : listaNominas.values()){
            // Lista { id : (id - (nombre empleado + apellido) + nomina + prestacion) }
            String data = "Id: " + i.get(0) + " NOMBRE: " + i.get(1) + " NOMINA: " + i.get(2) + " PRESTACION: " + i.get(3);
            
            model.add(index, data);
            index ++;
            
        }
        
        jListLiqMasiva.setModel(model);
        
    }
    
    private void listaEmpleado(){
        
        DefaultListModel model = new DefaultListModel();
        
        int index = 0;
        for (Empleado empleado : empleadoLista) {
            
            String data = (index+1) + ")  Id: " + empleado.getId() + " NOMBRE: " + empleado.getNombre() + " " + empleado.getApellido();
            
            model.add(index, data);
            index ++;
        }
        
        jListEmpleado.setModel(model);
        
    }

    private void actVistaEmpleado(){
        this.empleadoLista = mdEmpleado.listaEmpleado();
        this.listaEmpleado();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonConsultarEditar;
    private javax.swing.JButton jButtonConsultarEditar1;
    private javax.swing.JButton jButtonEditarEmpleado1;
    private javax.swing.JButton jButtonGenerarNomina;
    private javax.swing.JButton jButtonGuardarEmpleado;
    private javax.swing.JButton jButtonProcesoMasivo;
    private javax.swing.JCheckBox jCheckBoxauxTransp;
    private javax.swing.JCheckBox jCheckBoxauxTransp1;
    private javax.swing.JCheckBox jCheckBoxauxTransp2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelApellido1;
    private javax.swing.JLabel jLabelApellido2;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelCodigo1;
    private javax.swing.JLabel jLabelCodigo2;
    private javax.swing.JLabel jLabelInfNomina;
    private javax.swing.JLabel jLabelInfNomina1;
    private javax.swing.JLabel jLabelInfNomina2;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JLabel jLabelNombre2;
    private javax.swing.JLabel jLabelSalario;
    private javax.swing.JLabel jLabelSalario1;
    private javax.swing.JLabel jLabelSalario2;
    private javax.swing.JLabel jLabelTotalNomina;
    private javax.swing.JLabel jLabelTotalPrestacion;
    private javax.swing.JLabel jLabelvlrHoraExtra;
    private javax.swing.JLabel jLabelvlrHoraExtra1;
    private javax.swing.JLabel jLabelvlrHoraExtra2;
    private javax.swing.JList<String> jListEmpleado;
    private javax.swing.JList<String> jListLiqMasiva;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelConsulta;
    private javax.swing.JPanel jPanelConsulta1;
    private javax.swing.JPanel jPanelConsulta2;
    private javax.swing.JPanel jPanelDatoSalario;
    private javax.swing.JPanel jPanelDatoSalario1;
    private javax.swing.JPanel jPanelDatoSalario2;
    private javax.swing.JPanel jPanelInfoEmpleado;
    private javax.swing.JPanel jPanelInfoEmpleadoCrear;
    private javax.swing.JPanel jPanelInfoEmpleadoCrear1;
    private javax.swing.JPanel jPanelLiqNomina;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPaneGrupo;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldApellido1;
    private javax.swing.JTextField jTextFieldApellido2;
    private javax.swing.JTextField jTextFieldCedula;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldCodigo1;
    private javax.swing.JTextField jTextFieldCodigo2;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNombre1;
    private javax.swing.JTextField jTextFieldNombre2;
    private javax.swing.JTextField jTextFieldNomina;
    private javax.swing.JTextField jTextFieldSalario;
    private javax.swing.JTextField jTextFieldSalario1;
    private javax.swing.JTextField jTextFieldSalario2;
    private javax.swing.JTextField jTextFieldTotalPrestaciones;
    private javax.swing.JTextField jTextFieldvlrHoraExtra;
    private javax.swing.JTextField jTextFieldvlrHoraExtra1;
    private javax.swing.JTextField jTextFieldvlrHoraExtra2;
    // End of variables declaration//GEN-END:variables
}
